export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_WITH_EMAIL_LOADING = 'LOGIN_WITH_EMAIL_LOADING';
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAIL = 'LOGIN_WITH_EMAIL_FAIL';

export const REGISTER_WITH_EMAIL_LOADING = 'REGISTER_WITH_EMAIL_LOADING';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAIL = 'REGISTER_WITH_EMAIL_FAIL';

export const ME_LOADING = 'ME_LOADING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAIL = 'ME_FAIL';

export const GET_FEATURE = 'GET_FEATURE';
export const GET_PROFILE = 'GET_PROFILE';

export const GET_MESSAGES_LOADING = 'GET_MESSAGES_LOADING';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';

export const ADD_MESSAGE_LOADING = 'ADD_MESSAGE_LOADING';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAIL = 'ADD_MESSAGE_FAIL';

export const DELETE_MESSAGE_LOADING = 'DELETE_MESSAGE_LOADING';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';

export const EDIT_MESSAGE_LOADING = 'EDIT_MESSAGE_LOADING';
export const EDIT_MESSAGE_SUCCESS = 'EDIT_MESSAGE_SUCCESS';
export const EDIT_MESSAGE_FAIL = 'EDIT_MESSAGE_FAIL';
export const CLEAR_MESSAGE_ERROR = 'CLEAR_MESSAGE_ERROR';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const RESEED_DATABASE_LOADING = 'RESEED_DATABASE_LOADING';
export const RESEED_DATABASE_SUCCESS = 'RESEED_DATABASE_SUCCESS';
export const RESEED_DATABASE_FAIL = 'RESEED_DATABASE_FAIL';

export const GET_TODO_LOADING = 'GET_TODO_LOADING';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_FAIL = 'GET_TODO_FAIL';

export const GET_TODO_ITEM_LOADING = 'GET_TODO_ITEM_LOADING';
export const GET_TODO_ITEM_SUCCESS = 'GET_TODO_ITEM_SUCCESS';
export const GET_TODO_ITEM_FAIL = 'GET_TODO_ITEM_FAIL';

export const CREATE_TODO_OBJ_LOADING = 'CREATE_TODO_OBJ_LOADING'; 
export const CREATE_TODO_OBJ_SUCCESS = 'CREATE_TODO_OBJ_SUCCESS'; 
export const CREATE_TODO_OBJ_FAIL = 'CREATE_TODO_OBJ_FAIL'; 

export const ADD_TODO_LIST_LOADING = 'CREATE_TODO_LIST_LOADING'; 
export const ADD_TODO_LIST_SUCCESS = 'CREATE_TODO_LIST_SUCCESS'; 
export const ADD_TODO_LIST_FAIL = 'CREATE_TODO_LIST_FAIL';

export const ADD_TODO_LIST_ITEM_LOADING = 'ADD_TODO_LIST_ITEM_LOADING'; 
export const ADD_TODO_LIST_ITEM_SUCCESS = 'ADD_TODO_LIST_ITEM_SUCCESS'; 
export const ADD_TODO_LIST_ITEM_FAIL = 'ADD_TODO_LIST_ITEM_FAIL'; 

export const EDIT_TODO_LIST_LOADING = 'EDIT_TODO_LIST_LOADING';
export const EDIT_TODO_LIST_SUCCESS = 'EDIT_TODO_LIST_SUCCESS';
export const EDIT_TODO_LIST_FAIL = 'EDIT_TODO_LIST_FAIL';

export const EDIT_TODO_LIST_ITEM_LOADING = 'EDIT_TODO_LIST_ITEM_LOADING';
export const EDIT_TODO_LIST_ITEM_SUCCESS = 'EDIT_TODO_LIST_ITEM_SUCCESS';
export const EDIT_TODO_LIST_ITEM_FAIL = 'EDIT_TODO_LIST_ITEM_FAIL';

export const EDIT_TODO_LIST_ITEM_CHECKED_LOADING = 'EDIT_TODO_LIST_ITEM_CHECKED_LOADING';
export const EDIT_TODO_LIST_ITEM_CHECKED_SUCCESS = 'EDIT_TODO_LIST_ITEM_CHECKED_SUCCESS';
export const EDIT_TODO_LIST_ITEM_CHECKED_FAIL = 'EDIT_TODO_LIST_ITEM_CHECKED_FAIL';

export const DELETE_TODO_LIST_LOADING = 'DELETE_TODO_LIST_LOADING'; 
export const DELETE_TODO_LIST_SUCCESS = 'DELETE_TODO_LIST_SUCCESS'; 
export const DELETE_TODO_LIST_FAIL = 'DELETE_TODO_LIST_FAIL';

export const DELETE_TODO_LIST_ITEM_LOADING = 'EDIT_TODO_LIST_ITEM_LOADING';
export const DELETE_TODO_LIST_ITEM_SUCCESS = 'EDIT_TODO_LIST_ITEM_SUCCESS';
export const DELETE_TODO_LIST_ITEM_FAIL = 'EDIT_TODO_LIST_ITEM_FAIL';
